### ISSUE TITLE
BUG: Fix ramp air time

### ISSUE THREAD

**Issue by trains2050** [tmalahie/mkpc#1]
Reported by nate:
Ramps seem to be giving random air time and do not work on higher CC
Will check code and up]date the issue

**Comment by tmalahieude** [comment]
This one won't be obvious to fix but maybe you can try
The reason why it's random is because I had to make you go less high than in 150cc so that y97 don't go too far, but high enough so that you still jump higher than the walls. So it's a kind of compromise I had to make and I can see why it's confusing for players

**Comment by tmalahieude** [comment]
For info it's this part of the code:
```
var height0 = pJump * 1.5;
oKart.heightinc = height0 * Math.pow(cappedRelSpeed(oKart), -0.7);
if ((fSelectedClass > 1) && (0.7*oKart.heightinc*oKart.heightinc < 1.175))
    oKart.z = Math.max(oKart.z, height0*height0 - oKart.heightinc*oKart.heightinc);
```
If you can do better I'm interested though

**Comment by tmalahie** [comment]
GambaDTNT sent useful videos:
https://cdn.discordapp.com/attachments/308979137480097793/854659924470923274/Screen_Recording_2021-06-16_at_7.50.47_pm.mov
https://cdn.discordapp.com/attachments/308979137480097793/854659942153060352/Screen_Recording_2021-06-16_at_7.51.42_pm.mov
Here ramp air time seems inconsistent for unknown reasons, that's something that we probably can investigate.

**Comment by trains2050** [comment]
yes, we can, let see what I can do about it next week

**Comment by tmalahie** [comment]
Fixed it by adding an extra check when in >150cc. Cf commit [26f874b4b](https://github.com/tmalahie/mkpc/commit/26f874b4b5bd02d6ead31e6a588cfe89d27c6fe8)
